version: '3.1'
services:
  app:
    container_name: parking-tariffservice
    image: parking-tariffservice
    build: ./
    environment:
      - DB_SERVER="postgres-parking"
      - POSTGRES_PASSWORD="test"
      - POSTGRES_USER="test"
      - POSTGRES_DB="Parking"
      - DB_SCHEMA="tariff_schema"
    ports:
      - 8082:8082
      #depends_on:
      #- postgres-parking